// Public module — the OWNER-SIDE session administration PORT (RLS-scoped writes on
// public_sessions + its invite / project-link tables + the eligible-projects read).
// Distinct from PublicSessionRepository, which serves the anonymous /p/<token>
// gate. The /sessions management routes go through this contract.

import type { PublicSession, PublicSessionInvite } from "@/lib/shared/types"

/** The fields needed to create a session (token generated by the route). */
export interface NewPublicSession {
    teamId: string
    userId: string
    token: string
    accessMode: "link" | "invite"
    submissionsVisibility: "all" | "own"
    groupId: string | null
    name: string
    title: string | null
    description: string | null
    startAt: string | null
    endAt: string | null
}

/** The mutable fields of a session. */
export interface PublicSessionPatch {
    enabled?: boolean
    access_mode?: "link" | "invite"
    submissions_visibility?: "all" | "own"
    group_id?: string | null
    name?: string
    title?: string | null
    description?: string | null
    start_at?: string | null
    end_at?: string | null
}

/** Add-project outcomes: the FK/unique/trigger cases the routes map to 4xxs.
 *  "integration_disabled" = the project lacks the public integration (23514). */
export type SessionProjectResult = "ok" | "duplicate" | "integration_disabled"

export interface PublicSessionAdminRepository {
    /** The team's sessions, newest first. THROWS RepositoryError. */
    listForTeam(teamId: string): Promise<PublicSession[]>
    /** A session by id, or null when absent. THROWS on a query failure. */
    findById(id: string): Promise<PublicSession | null>
    /** Create a session; returns the row. THROWS. */
    create(input: NewPublicSession): Promise<PublicSession>
    /** Apply a patch; returns the updated row. THROWS. */
    update(id: string, patch: PublicSessionPatch): Promise<PublicSession>
    /** Delete a session. THROWS. */
    delete(id: string): Promise<void>
    /** Rotate a session's public token; returns the updated row. THROWS. */
    rotateToken(id: string, token: string): Promise<PublicSession>

    // ─── project coverage (public_session_projects) ──────────────────────────
    /** Member project id+name for a session. FAIL-SAFE ([] on error). */
    listProjectNames(sessionId: string): Promise<{ id: string; name: string }[]>
    /** Member project names keyed by session, for the overview list. FAIL-SAFE. */
    listProjectNamesBySessions(sessionIds: string[]): Promise<{ session_id: string; name: string }[]>
    /** Add one project to a session ("duplicate" 23505 / "integration_disabled"
     *  23514). Throws on any other failure. */
    addProject(sessionId: string, projectId: string): Promise<SessionProjectResult>
    /** Bulk-add projects on create ("integration_disabled" 23514). Throws otherwise. */
    addProjects(sessionId: string, projectIds: string[]): Promise<"ok" | "integration_disabled">
    /** Remove one project from a session. THROWS on failure. */
    removeProject(sessionId: string, projectId: string): Promise<void>

    /** Drop a project from EVERY session covering it (used when its public
     *  integration is disabled). THROWS on failure. */
    removeProjectFromAllSessions(projectId: string): Promise<void>

    // ─── invite whitelist (public_session_invites) ───────────────────────────
    /** Whitelisted invite emails for a session, oldest first. THROWS on failure. */
    listInvites(sessionId: string): Promise<PublicSessionInvite[]>
    /** Upsert invite emails (ignore-duplicates); returns the affected rows. THROWS. */
    addInvites(sessionId: string, emails: string[]): Promise<PublicSessionInvite[]>
    /** Ensure the owner's email is whitelisted (idempotent). BEST-EFFORT — swallows
     *  errors, matching the route's fire-and-forget upsert. */
    addOwnerInvite(sessionId: string, email: string): Promise<void>
    /** Remove one invite email. THROWS on failure. */
    removeInvite(sessionId: string, email: string): Promise<void>

    // ─── eligible projects (project_public_integration!inner) ────────────────
    /** Projects with the public integration enabled — eligible for a new session.
     *  FAIL-SAFE ([] on error). */
    listEligibleProjects(teamId: string): Promise<{ id: string; name: string }[]>
}
